"""Report export — JSON + Markdown (reuse the raidkit engine) + a styled HTML report."""
from __future__ import annotations

from datetime import datetime
from html import escape

from raidkit.report import Finding, Severity, counts, to_json, to_markdown

__all__ = ["to_json", "to_markdown", "to_html"]

_SEV_COLOR = {
    "CRITICAL": "#8e1616", "HIGH": "#c62828", "MEDIUM": "#c77800",
    "LOW": "#1565c0", "INFO": "#5f6368",
}


def to_html(target: str, findings: list[Finding], when: datetime) -> str:
    findings = sorted(findings, key=lambda f: f.severity, reverse=True)
    c = counts(findings)
    chips = "".join(
        f'<span class="chip" style="background:{_SEV_COLOR[s]}">{s} {c[s]}</span>'
        for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO")
    )
    rows = "".join(
        f"<tr>"
        f'<td><span class="sev" style="background:{_SEV_COLOR[f.severity.name]}">{f.severity.name}</span></td>'
        f"<td>{escape(f.check)}</td>"
        f"<td><strong>{escape(f.title)}</strong>"
        + (f'<div class="ev">{escape(f.evidence)}</div>' if f.evidence else "")
        + "</td>"
        f"<td>{escape(f.remediation)}</td>"
        f"</tr>"
        for f in findings
    )
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>RaidDeck report — {escape(target)}</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Arial,sans-serif;margin:40px;color:#1a1a1a;background:#fafafa}}
 h1{{margin:0 0 4px}} .meta{{color:#666;margin-bottom:16px}}
 .chip,.sev{{color:#fff;border-radius:6px;padding:3px 10px;font-weight:700;font-size:13px}}
 .chip{{margin-right:8px;display:inline-block}}
 table{{border-collapse:collapse;width:100%;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.1)}}
 th,td{{text-align:left;padding:12px 14px;border-bottom:1px solid #eee;vertical-align:top}}
 th{{background:#f3f3f3}} .ev{{color:#777;font-size:13px;margin-top:4px;font-family:monospace}}
 footer{{margin-top:24px;color:#999;font-size:13px}}
</style></head><body>
<h1>RaidDeck scan report</h1>
<div class="meta"><strong>Target:</strong> {escape(target)} &middot; <strong>Scanned:</strong> {when.isoformat()}</div>
<div style="margin-bottom:18px">{chips}</div>
<table><thead><tr><th>Severity</th><th>Check</th><th>Finding</th><th>Fix</th></tr></thead>
<tbody>{rows}</tbody></table>
<footer>Generated by RaidDeck — an authorized, non-destructive white-hat security toolkit.</footer>
</body></html>"""
